description: 'This workflow consists of the following components:

  1. Receive the product_name as input in the InputProduct data model.

  2. Scrape the Amazon product reviews for the given product_name.

  3. Create a spreadsheet containing the scraped reviews.

  4. Return the spreadsheet_url as output in the OutputProductReviews data model.

  '
input-class: InputProduct
name: AmazonReviewScraperWorkflow
output-class: OutputProductReviews
parameters: {}
